<a href="https://colab.research.google.com/github/rsarpongstreetor/2DayCourse/blob/master/Copy_of_Data_processing_PhD_Jan_2024_RL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Download Data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import time
dffff=pd.read_csv('/content/drive/MyDrive/deep learning codes/EIAAPI_DOWNLOAD/solutions/mergedata/Cleaneddata.csv')

dffff = dffff.drop(dffff.columns[4], axis=1)
recentdatadate=dffff.index[-1]
dfffff= pd.DataFrame(dffff)

print(dfffff)
print(recentdatadate)

Mounted at /content/drive
       USD_SDR   OPEC  Brent    WTI  ('EER_EPD2DC_PF4_Y05LA_DPG',)  \
0     0.736561  30.05  30.31  31.97                          0.868   
1     0.740139  30.83  31.44  33.25                            NaN   
2          NaN    NaN    NaN    NaN                            NaN   
3          NaN    NaN    NaN    NaN                            NaN   
4     0.735686  30.70  31.44  32.28                          0.898   
...        ...    ...    ...    ...                            ...   
7690  0.751030  79.70  81.70  75.25                          2.206   
7691  0.751212  81.30    NaN    NaN                            NaN   
7692  0.750114  81.06    NaN    NaN                            NaN   
7693  0.750299  82.00    NaN    NaN                            NaN   
7694  0.750919    NaN    NaN    NaN                            NaN   

      ('EER_EPD2DXL0_PF4_RGC_DPG',)  ('EER_EPD2DXL0_PF4_Y35NY_DPG',)  \
0                             0.905                          

In [ ]:
print(dfffff.index)


RangeIndex(start=0, stop=7695, step=1)


## Ffilling of missing Data using Pandas.ffill






In [ ]:
dffffff=dfffff.ffill()
recenttdatadate=dffffff.index[-1]
print(recenttdatadate)

7694


## Slicing Fuel Prices to compute Rewards, Action Space and Probability of Action Space

In [ ]:
import tensorflow as tf
numberr = tf.constant(dffffff, tf.float64)
print(numberr)
y=numberr[:,4:]

tf.Tensor(
[[ 0.736561 30.05     30.31     ...  0.554     0.888     0.885   ]
 [ 0.740139 30.83     31.44     ...  0.554     0.888     0.885   ]
 [ 0.740139 30.83     31.44     ...  0.554     0.888     0.885   ]
 ...
 [ 0.750114 81.06     81.7      ...  2.086     2.689     2.301   ]
 [ 0.750299 82.       81.7      ...  2.086     2.689     2.301   ]
 [ 0.750919 82.       81.7      ...  2.086     2.689     2.301   ]], shape=(7695, 13), dtype=float64)


## Environment  Observations:Forex and Crude oil price  

---







In [ ]:
'''The retuns are calculated, States are avaible and the action space are also presented the action space is the price direction '''
import numpy as np

States=numberr[:,:4]
States=np.array(States)
print(States)

[[ 0.736561 30.05     30.31     31.97    ]
 [ 0.740139 30.83     31.44     33.25    ]
 [ 0.740139 30.83     31.44     33.25    ]
 ...
 [ 0.750114 81.06     81.7      75.25    ]
 [ 0.750299 82.       81.7      75.25    ]
 [ 0.750919 82.       81.7      75.25    ]]


## Returns

In [ ]:
''''The retuns are calculated, States are available, the two forms the independent variable and the action space are also presented the actioin space ( dependent variable) is the price direction
action space is the direction of the returns and the returns is the the differnce of the fuel price form aprevious chprious price. The reward  is defind as the absolut of the returns


x=
'''
x=np.array(y)
def returns(x):
  import numpy as np
  import array as arr
  import pandas as pd
  a =np.mean(x,axis=0)
  yx=[]
  xx=[]
  xx= np.vstack((a,x))
  xx=np.array(xx)
  K=xx.shape[0]
  L=xx.shape[1]
  yxxxx=np.zeros((K-1,L))
  for i in range(L):
   for k in range(K-1):
    yxxxx[k-1][i]=(xx[k+1,i]-xx[k,i])

  print(yxxxx)
  return yxxxx

RRRR=returns(x)
print(RRRR)
RRRR.shape


[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-1.07909071 -1.0426039  -1.06156244 ... -1.40414282 -1.06531267
  -1.06311358]]
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-1.07909071 -1.0426039  -1.06156244 ... -1.40414282 -1.06531267
  -1.06311358]]


(7695, 9)

## Reward computation

In [ ]:
''''The retuns are calculated, States are available, the two forms the independent variable and the action space are also presented the actioin space ( dependent variable) is the price direction
action space is the direction of the returns and the returns is the the differnce of the fuel price form aprevious chprious price. The reward  is defind as the absolut of the returns


x=
'''
x=np.array(y)
def reward(x):
  import numpy as np
  import array as arr
  import pandas as pd
  a =np.mean(x,axis=0)
  yx=[]
  xx=[]
  xx= np.vstack((a,x))
  xx=np.array(xx)
  K=xx.shape[0]
  L=xx.shape[1]
  yxx=np.zeros((K-1,L))
  for i in range(L):
   for k in range(K-1):
    yxx[k-1][i]=abs(xx[k+1,i]-xx[k,i])

  print(yxx)
  return yxx

RRw=reward(x)
print(RRw)
RRw.shape


[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [1.07909071 1.0426039  1.06156244 ... 1.40414282 1.06531267 1.06311358]]
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [1.07909071 1.0426039  1.06156244 ... 1.40414282 1.06531267 1.06311358]]


(7695, 9)

## Calculating Action Space

In [ ]:
#There are three action space which are up(+1), no change(0) and down(-1).
#We convert them to a (0,1, 2) space using the equation below  by addding 1.
#Apply actionss
        # 0 -1 = -1
        # 1 -1 = 0
        # 2 -1 = 1
"áctionssss finds the sign of the element of the matrix number"
def actionspace(x):
  import numpy as np
  import array as arr
  import pandas as pd
  a =np.mean(x,axis=0)
  yx=[]
  xx=[]
  xx= np.vstack((a,x))
  xx=np.array(xx)
  K=xx.shape[0]
  L=xx.shape[1]
  yxx=np.zeros((K-1,L))
  for i in range(L):
   for k in range(K-1):
    yx=xx[k+1,i]-xx[k,i]
    if yx>0:
      yxx[k-1][i]=2
    elif yx<0:
      yxx[k-1][i]=0
    else:
      yxx[k-1][i]=1
  print(yxx)
  return yxx

action= actionspace(RRw)
print(action)
action.shape




[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]
 [0. 0. 0. ... 0. 0. 0.]]


(7695, 9)

## Calculating Probability of Action space









In [ ]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import time
import collections
from collections import Counter
K=action.shape[0]
L=action.shape[1]
ps=[]
def probabilityaction(action):
  for i in range(L):
    ps.append(Counter(action[:,i]))
  pss=pd.DataFrame(ps)
  psss=pss.div(K)
  #print(psss)
  probaction=np.zeros((K,L))
  for i in range(len(ps)):
     for j in range(K):
        if action[j,i] == 0:
          probaction[j,i] = psss.iat[i,2]
        elif action[j,i] ==1:
          probaction[j,i] =psss.iat[i,0]
        else:
          probaction[j,i]=psss.iat[i,1]
        j += 1
     i+=1
  return probaction


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
ppp=probabilityaction(action )
print(ppp)

[[0.18037687 0.1814165  0.18076673 ... 0.18154646 0.18063678 0.18128655]
 [0.18037687 0.1814165  0.18076673 ... 0.18154646 0.18063678 0.18128655]
 [0.40844704 0.40870695 0.41130604 ... 0.41052632 0.41104613 0.40610786]
 ...
 [0.18037687 0.1814165  0.18076673 ... 0.18154646 0.18063678 0.18128655]
 [0.40844704 0.40870695 0.41130604 ... 0.41052632 0.41104613 0.40610786]
 [0.41117609 0.40987654 0.40792723 ... 0.40792723 0.40831709 0.41260559]]


##Agregating  computed variables varibles for preprossesing; Concantenating  Rewards,  Actions and Probabilty space  

In [ ]:
"""Normaliztion will be passed to the Neural network as which does it. """

##Normalizing Variables
from sklearn.preprocessing import normalize
Indep=np.hstack((RRw,action))
print(Indep)
#normalize matrix by rows
#Indep = normalize(Indep, axis=1, norm='l2')
#view normalized matrix
#print(Indep)
Indep.shape

[[0.         0.         0.         ... 1.         1.         1.        ]
 [0.         0.         0.         ... 1.         1.         1.        ]
 [0.         0.         0.         ... 2.         2.         2.        ]
 ...
 [0.         0.         0.         ... 1.         1.         1.        ]
 [0.         0.         0.         ... 2.         2.         2.        ]
 [1.07909071 1.0426039  1.06156244 ... 0.         0.         0.        ]]


(7695, 18)

## Concantenating All Variables







In [ ]:
Variables=np.hstack((dffffff,Indep))
Variables.shape
Var_df=pd.DataFrame(Variables)


In [ ]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import torch
from torch import tensor
import pandas as pd
''' Variables=(S r A)
number is made up of S, we'ved  worked out A, P(s_(t+1)) and r u  using  some
states,

# We stack r to S
# For the model, Action-space is the dependent variable
# We concatenate S and r to become the independent variable
'''

Variables.shape
VariablesPandas=pd.DataFrame(Variables)
vvmm=VariablesPandas.describe()
print(vvmm)
K=len(Variables[1])
M=len(Variables)
I=int((K-4)/3)
GGG=np.empty((M,7,I))
i=0



y = Variables[:,13:]

for i in range(I):
  ##States: Crude oil prices, Forex
  St=Variables[:,:int(4)]
  ##Fuel price
  Fp =(Variables[:, int(4 + I * 0 + i):int(5 + I * 0 + i)])
  # Reward
  RRw =(Variables[:, int(4 + I * 1 + i):int(5 + I * 1 + i)])
  # Action space,
  Act=(Variables[:, int(4 + I * 2 + i):int(5 + I * 2 + i)])
  ##Probability space
 # Prob=(Variables[:, int(4+I*3+i):int(5+I*3+i)])
  vvv=np.hstack((St,Fp,RRw, Act ))
  vvv=np.array(vvv)
  GGG[0:,0:,i]=vvv
  i+=1

  #vvv=np.hstack((Variables[:,:4+i],Variables[:,4+I*1+i:5+I*1+i],Variables[:,4+I*2+i:5+I*2+i],Variables[:,4+I*3+i:5+I*3+i]))





GGG=torch.tensor(GGG, device=torch.device('cpu'),dtype=torch.float32)
GGG.reshape(-1,1)


training_GGG,test_GGG = train_test_split(GGG, train_size =0.5, random_state=0)


print(training_GGG)
print(test_GGG)
DataDic=[training_GGG, test_GGG, GGG]
with open ('/content/drive/MyDrive/deep learning codes/EIAAPI_DOWNLOAD/solutions/mergedata/DataDic.pt', 'wb') as fpsp:
  torch.save(DataDic, fpsp)

                0            1            2            3            4   \
count  7695.000000  7695.000000  7695.000000  7695.000000  7695.000000   
mean      0.688006    69.883288    71.904144    68.269891     1.947091   
std       0.038017    26.419639    26.720515    23.454819     0.816054   
min       0.605660    12.220000     9.120000   -36.970000     0.228000   
25%       0.655161    49.600000    51.300000    49.680000     1.348000   
50%       0.688649    66.940000    68.940000    66.200000     1.880000   
75%       0.718610    90.940000    92.080000    86.600000     2.575500   
max       0.789356   140.800000   144.000000   145.200000     5.009000   

                5            6            7            8            9   ...  \
count  7695.000000  7695.000000  7695.000000  7695.000000  7695.000000  ...   
mean      1.947604     1.941562     1.961945     1.967427     1.956298  ...   
std       0.805367     0.808749     0.810041     0.811734     0.799045  ...   
min       0.20300

## Define labels/Targets/Dependent and Feateurs/Independent vairables Input structured into Tuples of Features  and Targets for Policy function

In [ ]:
#States: 0==Forex, 1=OPEC,2==Brent 3==WTI, 4=Fuelprice

def predata(x):
  import os
  import pandas as pd
  from torchvision.io import read_image
  from torch import tensor
  from torchvision.transforms import ToTensor
  from torch.utils.data import DataLoader
  GGG=x

  i=0
  GGGGG=[]
  K=x.shape[2]

  for i in range(K):
    GGGG=x[:,:,i]



    images = GGGG[0:,0:5]
    images.index_add

    image = images.clone().detach()
    #GGGGG.append(image, reshape(label,(-1,1)))
    GGGGG.append((image))


    i += 1
  # return train_dataloader,test_dataloader
    GGGGG
  return GGGGG

In [ ]:
#States: 0==Forex, 1=OPEC,2==Brent 3==WTI, 4=Fuelprice  5==Reward space  6==action space 7==Probability space

def predataP(x):
  import os
  import pandas as pd
  from torchvision.io import read_image
  from torch import tensor
  from torchvision.transforms import ToTensor
  from torch.utils.data import DataLoader
  GGG=x

  i=0
  GGGGG=[]
  K=x.shape[2]

  for i in range(K):
    GGGG=x[:,:,i]



    images = GGGG[0:,0:5]
    images.index_add

    image = images.clone().detach()
    #GGGGG.append(image, reshape(label,(-1,1)))
    GGGGG.append((image))


    i += 1
  # return train_dataloader,test_dataloader
    GGGGG
  return GGGGG




In [ ]:
GGGGGenv=predataP(GGG)
with open ('/content/drive/MyDrive/deep learning codes/EIAAPI_DOWNLOAD/solutions/mergedata/GGGGGenv.pt', 'wb') as fpsp:
  torch.save(GGGGGenv, fpsp)

#Train_data_Policy

In [ ]:
tttrains_DataGGGP=predataP(training_GGG)

print(tttrains_DataGGGP)
with open ('/content/drive/MyDrive/deep learning codes/EIAAPI_DOWNLOAD/solutions/mergedata/tttrains_DataGGGP.pt', 'wb') as fpp:
  torch.save(tttrains_DataGGGP, fpp)



[tensor([[  0.7118,  74.9000,  76.2500,  73.4400,   2.1340],
        [  0.6486, 122.8000, 125.2000, 106.4400,   1.2840],
        [  0.6661, 103.1000, 104.0000,  92.7500,   2.6380],
        ...,
        [  0.6534,  72.7000,  78.1000,  73.9000,   2.3490],
        [  0.6559,  75.2000,  76.9000,  79.7500,   2.0830],
        [  0.6777,  73.8000,  76.2000,  78.4400,   2.0980]]), tensor([[  0.7118,  74.9000,  76.2500,  73.4400,   2.2310],
        [  0.6486, 122.8000, 125.2000, 106.4400,   3.3790],
        [  0.6661, 103.1000, 104.0000,  92.7500,   0.9090],
        ...,
        [  0.6534,  72.7000,  78.1000,  73.9000,   2.0520],
        [  0.6559,  75.2000,  76.9000,  79.7500,   2.1250],
        [  0.6777,  73.8000,  76.2000,  78.4400,   2.1050]]), tensor([[  0.7118,  74.9000,  76.2500,  73.4400,   2.1140],
        [  0.6486, 122.8000, 125.2000, 106.4400,   3.2880],
        [  0.6661, 103.1000, 104.0000,  92.7500,   2.9720],
        ...,
        [  0.6534,  72.7000,  78.1000,  73.9000,   2.071

# Test_data_Policy

In [ ]:
test_dataGGGP=predataP(test_GGG)
print(test_dataGGGP)

with open ('/content/drive/MyDrive/deep learning codes/EIAAPI_DOWNLOAD/solutions/mergedata/test_dataGGGP.pt', 'wb') as fppp:
  torch.save(test_dataGGGP, fppp)

[tensor([[ 0.7243, 50.9000, 52.7800, 50.3000,  1.6110],
        [ 0.7082, 59.9700, 59.4000, 59.6200,  2.0030],
        [ 0.6610, 74.4400, 77.2500, 78.7000,  2.0880],
        ...,
        [ 0.6828, 31.8100, 33.3000, 35.8000,  1.3750],
        [ 0.6889, 64.5000, 66.0600, 63.3400,  1.9850],
        [ 0.6730, 29.8800, 30.3000, 32.5000,  0.8520]]), tensor([[ 0.7243, 50.9000, 52.7800, 50.3000,  1.5930],
        [ 0.7082, 59.9700, 59.4000, 59.6200,  1.9850],
        [ 0.6610, 74.4400, 77.2500, 78.7000,  2.0790],
        ...,
        [ 0.6828, 31.8100, 33.3000, 35.8000,  0.9440],
        [ 0.6889, 64.5000, 66.0600, 63.3400,  1.9810],
        [ 0.6730, 29.8800, 30.3000, 32.5000,  1.0600]]), tensor([[ 0.7243, 50.9000, 52.7800, 50.3000,  1.5980],
        [ 0.7082, 59.9700, 59.4000, 59.6200,  1.7490],
        [ 0.6610, 74.4400, 77.2500, 78.7000,  2.1430],
        ...,
        [ 0.6828, 31.8100, 33.3000, 35.8000,  1.3300],
        [ 0.6889, 64.5000, 66.0600, 63.3400,  2.1940],
        [ 0.6730, 29.






# DataLoader_Policy

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
from torch.utils.data import DataLoader
tttrains_dataloaderP = DataLoader(tttrains_DataGGGP, batch_size=364, shuffle=True)
test_dataloaderP = DataLoader(test_dataGGGP, batch_size=364, shuffle=True)
print(test_dataloaderP)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Define labels/Targets/Dependent and Feateurs/Independent vairables Input structured into Tuples of Features  and Targets for State/Step function

In [ ]:
#States: 0==Forex, 1=OPEC,2==Brent 3==WTI, 4=Fuelprice  5==Reward space  6==Reward space 7==Probability space

def predataS(x):
  import os
  import pandas as pd
  from torchvision.io import read_image
  from torch import tensor
  from torchvision.transforms import ToTensor
  from torch.utils.data import DataLoader
  GGG=x

  i=0
  GGGGG=[]
  K=x.shape[2]

  for i in range(K):
    GGGG=x[:,:,i]


    labels = GGGG[0:,7:8]
    labels.index_add
    images = GGGG[0:,0:7]
    images.index_add
    label = labels.clone().detach()
    image = images.clone().detach()
    #GGGGG.append(image, reshape(label,(-1,1)))
    GGGGG.append((image,label))


    i += 1
  # return train_dataloader,test_dataloader
    GGGGG
  return GGGGG

  with open ('/content/drive/MyDrive/deep learning codes/EIAAPI_DOWNLOAD/solutions/mergedata/GGGGG.pt ', 'wb') as fpppps:
    torch.save(GGGGG,fpppps)

#Train_data_State

In [ ]:
train_DataGGGS=predataS(training_GGG)

print(train_DataGGGS)
with open ('/content/drive/MyDrive/deep learning codes/EIAAPI_DOWNLOAD/solutions/mergedata/train_DataGGGS.pt ', 'wb') as fpps:
  torch.save(train_DataGGGS, fpps)

[(tensor([[7.1178e-01, 7.4900e+01, 7.6250e+01,  ..., 2.1340e+00, 2.9000e-02,
         0.0000e+00],
        [6.4858e-01, 1.2280e+02, 1.2520e+02,  ..., 1.2840e+00, 2.0560e+00,
         0.0000e+00],
        [6.6609e-01, 1.0310e+02, 1.0400e+02,  ..., 2.6380e+00, 0.0000e+00,
         1.0000e+00],
        ...,
        [6.5339e-01, 7.2700e+01, 7.8100e+01,  ..., 2.3490e+00, 0.0000e+00,
         1.0000e+00],
        [6.5589e-01, 7.5200e+01, 7.6900e+01,  ..., 2.0830e+00, 2.2000e-02,
         0.0000e+00],
        [6.7774e-01, 7.3800e+01, 7.6200e+01,  ..., 2.0980e+00, 0.0000e+00,
         2.0000e+00]]), tensor([], size=(3847, 0))), (tensor([[7.1178e-01, 7.4900e+01, 7.6250e+01,  ..., 2.2310e+00, 1.9100e-01,
         0.0000e+00],
        [6.4858e-01, 1.2280e+02, 1.2520e+02,  ..., 3.3790e+00, 9.9000e-02,
         0.0000e+00],
        [6.6609e-01, 1.0310e+02, 1.0400e+02,  ..., 9.0900e-01, 0.0000e+00,
         1.0000e+00],
        ...,
        [6.5339e-01, 7.2700e+01, 7.8100e+01,  ..., 2.0520e+00, 0.00

# Test_data_State

In [ ]:
test_dataGGGS=predataS(test_GGG)
print(test_dataGGGS)


with open ('/content/drive/MyDrive/deep learning codes/EIAAPI_DOWNLOAD/solutions/mergedata/test_dataGGGS.pt', 'wb') as fppps:
  torch.save(test_dataGGGS, fppps)

[(tensor([[7.2432e-01, 5.0900e+01, 5.2780e+01,  ..., 1.6110e+00, 7.4000e-02,
         2.0000e+00],
        [7.0816e-01, 5.9970e+01, 5.9400e+01,  ..., 2.0030e+00, 1.0100e-01,
         0.0000e+00],
        [6.6096e-01, 7.4440e+01, 7.7250e+01,  ..., 2.0880e+00, 0.0000e+00,
         2.0000e+00],
        ...,
        [6.8281e-01, 3.1810e+01, 3.3300e+01,  ..., 1.3750e+00, 4.4800e-01,
         0.0000e+00],
        [6.8891e-01, 6.4500e+01, 6.6060e+01,  ..., 1.9850e+00, 6.9000e-02,
         0.0000e+00],
        [6.7296e-01, 2.9880e+01, 3.0300e+01,  ..., 8.5200e-01, 0.0000e+00,
         1.0000e+00]]), tensor([], size=(3848, 0))), (tensor([[7.2432e-01, 5.0900e+01, 5.2780e+01,  ..., 1.5930e+00, 9.3300e-01,
         2.0000e+00],
        [7.0816e-01, 5.9970e+01, 5.9400e+01,  ..., 1.9850e+00, 2.4100e-01,
         2.0000e+00],
        [6.6096e-01, 7.4440e+01, 7.7250e+01,  ..., 2.0790e+00, 0.0000e+00,
         2.0000e+00],
        ...,
        [6.8281e-01, 3.1810e+01, 3.3300e+01,  ..., 9.4400e-01, 1.66

# DataLoader_State

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
from torch.utils.data import DataLoader
Train_dataloaderS = DataLoader(train_DataGGGS, batch_size=364, shuffle=True)
test_dataloaderS = DataLoader(test_dataGGGS, batch_size=364, shuffle=True)



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
