<a href="https://colab.research.google.com/github/rsarpongstreetor/2DayCourse/blob/master/FuelpriceEnvFeb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gymnasium
!pip3 install gym-examples
!pip install stable_baselines3
!pip install gym[all]
!pip install ipython-autotime
%load_ext autotime
!pip install plotly


ERROR: Could not find a version that satisfies the requirement gym-examples (from versions: none)
ERROR: No matching distribution found for gym-examples
  Using cached mujoco_py-2.1.2.14-py3-none-any.whl (2.4 MB)
  Using cached box2d-py-2.3.5.tar.gz (374 kB)
  Preparing metadata (setup.py) ... done
  Using cached mujoco-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
  Using cached pygame-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
  Using cached swig-4.2.0-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.9 MB)
  Using cached pytest-7.0.1-py3-none-any.whl (296 kB)
  Using cached ale_py-0.7.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
  Using cached lz4-4.3.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
  Using cached fasteners-0.19-py3-none-any.whl (18 kB)
  error: subprocess-exited-with-error
  
  × python setup.py bdi

In [ ]:
!pip3 install gymnasium[mujoco]

time: 4.72 s (started: 2024-02-13 06:33:59 +00:00)


In [ ]:
import numpy as np
import pygame
from gym import Env
from gym.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete
import random
import os
import gymnasium as gym
from gymnasium import spaces
import torch
from torch import tensor
import google.colab
from stable_baselines3.common.env_checker import check_env
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
import math
import matplotlib
import matplotlib.pyplot as plt
from collections import namedtuple, deque
from itertools import count
import plotly.express as px
import pandas as pd
google.colab.drive.mount('/content/drive')





k=2


class FuelpriceEnv():

  #Initialize
  def __init__(self):
        # Observations are dictionaries with the agent's Observation which are.
        # Forex, Crude oil pric, Fuel price, reward, action
          self.action_space = Discrete(3)
          self.k=k
          self.observation_space=spaces.Tuple([spaces.Box(0,1,shape=(1, ), dtype=np.float32),
                                spaces.Box(0,145,shape=(1, ), dtype=np.float32),
                                spaces.Box(0,145,shape=(1, ), dtype=np.float32),
                                spaces.Box(0,145,shape=(1, ), dtype=np.float32),
                                spaces.Box(0,6,shape=(1, ), dtype=np.float32),


                                ])





          #self.action=np.zeros(1)
          self.Terminationpoint=[]
          self.fuelprice=np.zeros(1)
          self.reward=np.zeros(1)
          self.state=np.zeros(5)
          #self.observation=np.matrix([1,7], np.float32)
  def _downl_Data(self):
        with open('/content/drive/MyDrive/deep learning codes/EIAAPI_DOWNLOAD/solutions/mergedata/DataDic.pt','rb') as rpp:
          DataDic = torch.load(rpp)
        DDataDic=DataDic[2]
        DDDDataDic=DDataDic[:,:,self.k]
        return DDDDataDic



        # We have 3 actions, corresponding to "increase", "decrease", "no change " in fuel price
          #self.action_space = spaces.Discrete(3)


  def _get_obs(self):
        DDDataDic=self._downl_Data()
        self.observation=DDDataDic[np.random.choice(DDDataDic.shape[0], 1, replace=False),:].numpy().astype(np.float32)
        self.Terminationpoint.append(self.observation)
        return self.observation,







        #"""The following dictionary maps actions from `self.action_space` to the price  of fuel price changes ."""

  	# Tuple index(0-Forex, 1-Crude oil pric, 2-Fuel price, 3-reward, 4-action)
    #Apply action
        # 0 -1 = -1 decrease fuel price
        # 1 -1 = 0  no change in fuel price
        # 2 -1 = 1  increase fuel price



  def step(self, action):
      action=self.action_space.sample()
      aaaaa =self._get_obs()
      aaaaaa=aaaaa[0][0]
      action=aaaaaa[6]

      action-=1
      action.reshape
      self.fuelprice=aaaaaa[4]-(aaaaaa[5] * action)
      self.state=np.hstack([aaaaaa[0:4],self.fuelprice])
      self.reward=aaaaaa[5]
      reward=self.reward

        # Check if sampling is done
      DDDataDic = self._downl_Data()

      DDDD = pd.DataFrame(DDDataDic)
      self.Terminationpoint
       #self.Terminationpoint.iter
      if len(self.Terminationpoint) == DDDD.shape[0] :
        done = True
      else:
        done = False

        # Set placeholder for info
      info = {}
        # Return step information
      return self.state , reward, done, info


#= pd.DataFrame(self.Terminationpoint)



  def render(self):
       # Implement viz
      pass


      # df=pd.DataFrame(self.Terminationpoint, colums=[["Forex","Brent","WTI","OPEC","Fuelprice","reward" ,"action"]])
        #fig = px.line(df, x='index', y='value', color='variable', symbol="variable")
        #fig.show()
       # return fig.show()


  def reset(self):
        # Reset observation
        # Tuple index(0-Forex, 1-Crude oil pric, 2-Fuel price, 3-reward, 4-action)
        self.state=[]
        self.state=self.observation_space.sample()
        self.state=np.hstack(self.state)
        info = {}
        #self.observation_space1 = (self.observation_space[2].sample()) - (self.observation_space[3].sample() * self.observation_space[4].sample()).astype(np.float64)
        #self.state = self.state=np.concatenate([self.observation_space[0], self.observation_space[1],self.observation_space[2],])

        return self.state, info


  def close(self):
       pygame.display.quit()
       pygame.quit()














      #"""Sutton, R. S. (1996). Generalization in Reinforcement Learning: Successful Examples Using Sparse Coarse Coding. In D. Touretzky, M. C. Mozer, & M. Hasselmo (Eds.), Advances in Neural Information Processing Systems (Vol. 8). MIT Press. https://proceedings.neurips.cc/paper/1995/file/8f1d43620bc6bb580df6e80b0dc05c48-Paper.pdf

      #Sutton, R. S., Barto, A. G. (2018 ). Reinforcement Learning: An Introduction. The MIT Press."""



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
time: 2.84 s (started: 2024-02-13 06:37:00 +00:00)


In [ ]:
# Import the necessary module
#!pip install gym

#Import the environment class
#from gym import Env
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        action = env.action_space
        n_state, reward, done, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()




In [ ]:
env = FuelpriceEnv()

time: 1.36 ms (started: 2024-02-13 06:37:06 +00:00)


In [ ]:
env.step(action)

(array([ 0.710446  , 59.97000122, 61.65999985, 61.06000137,  2.22199997]),
 0.429,
 False,
 {})

time: 17.2 ms (started: 2024-02-13 06:38:28 +00:00)


In [ ]:
env.render()

time: 295 µs (started: 2024-02-13 06:38:33 +00:00)


In [ ]:
env.reset()

(array([  0.34723684, 139.4288    , 131.72397   ,   5.942569  ,
          5.7513666 ], dtype=float32),
 {})

time: 3.89 ms (started: 2024-02-13 06:38:44 +00:00)


In [ ]:
env.close()

time: 19.4 ms (started: 2024-02-12 05:40:04 +00:00)


In [ ]:
env.observation_space.sample()

(array([0.05788877], dtype=float32),
 array([67.22421], dtype=float32),
 array([30.781115], dtype=float32),
 array([74.431404], dtype=float32),
 array([4.222523], dtype=float32))

time: 8.87 ms (started: 2024-02-12 10:59:01 +00:00)


In [ ]:
aa=env._get_obs()


In [ ]:
aaa=aa

print(aaa)


[[[ 0.708393 81.6      81.1      80.8       2.415     2.511     0.087   ]]]
time: 1.59 ms (started: 2024-02-12 10:59:20 +00:00)


In [ ]:
from setuptools import setup

setup(
    name="gym_utppjt",
    version="0.0.1",
    install_requires=["gymnasium==0.26.0", "pygame==2.1.0"],
)

In [ ]:
from gymnasium.envs.registration import register

register(
     id="gym_utppjt/FuelpriceEnv-v1",
     entry_point="gym_gym_utppjt.envs:FuelpriceEnv",
     max_episode_steps=300,
)

In [ ]:
env = gym.make(FuelpriceEnv)

In [ ]:
import gymnasium as gym
import gym
env = gym.make('gym_gym_utppjt/FuelpriceEnv-v0')

gym-examples/gym_examples/FuelpriceEnv-v0/__init__.py

In [ ]:
env.reset()

# Initialize the score
score = 0

# Run the environment for a certain number of steps
for episode in range(10):
    # Reset the environment at the beginning of each episode
    env.reset()

    # Initialize the done flag
    done = False

    # Run the environment until it's done
    while not done:
        # Render the environment
        env.render()

        # Get the action space
        action = env.action_space

        # Take a random action
        action = env.action_space.sample()

        # Take a step in the environment
        n_state, reward, done, info = env.step(action)

        # Update the score
        score += reward

    # Print the episode and score
    print('Episode:{} Score:{}'.format(episode, score))

# Close the environment
env.close()

Episode:0 Score:1911.236001428333


KeyboardInterrupt: 

time: 41min 53s (started: 2024-02-13 06:39:20 +00:00)


In [ ]:
DDDataDic=env._downl_Data()
print(DDDataDic)
DDDataDic.shape[0]

tensor([[ 0.7366, 30.0500, 30.3100,  ...,  0.8800,  0.8850,  0.0000],
        [ 0.7401, 30.8300, 31.4400,  ...,  0.8800,  0.8850,  0.0000],
        [ 0.7401, 30.8300, 31.4400,  ...,  0.8800,  0.8850,  0.0000],
        ...,
        [ 0.7501, 81.0600, 81.7000,  ...,  2.5960,  2.3010,  0.0000],
        [ 0.7503, 82.0000, 81.7000,  ...,  2.5960,  2.3010,  0.0000],
        [ 0.7509, 82.0000, 81.7000,  ...,  2.5960,  2.3010,  1.0383]])


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


7695

time: 23.1 ms (started: 2024-02-12 10:12:57 +00:00)


In [ ]:
ebabs=env.Terminationpoint
len(ebabs)

0

time: 4.84 ms (started: 2024-02-12 11:01:32 +00:00)


In [ ]:
env.state

array([  0.3966738,  21.354975 ,  41.046642 , 126.75393  ,   5.6953325],
      dtype=float32)

time: 4.65 ms (started: 2024-02-12 11:01:25 +00:00)


In [ ]:
env.reward

In [ ]:
llaa=env._downl_Data()
print(llaa)

tensor([[ 0.7366, 30.0500, 30.3100,  ...,  0.8800,  0.0000,  1.0000],
        [ 0.7401, 30.8300, 31.4400,  ...,  0.8800,  0.0000,  1.0000],
        [ 0.7401, 30.8300, 31.4400,  ...,  0.8800,  0.0000,  2.0000],
        ...,
        [ 0.7501, 81.0600, 81.7000,  ...,  2.5960,  0.0000,  1.0000],
        [ 0.7503, 82.0000, 81.7000,  ...,  2.5960,  0.0000,  2.0000],
        [ 0.7509, 82.0000, 81.7000,  ...,  2.5960,  1.0616,  0.0000]])
time: 78.8 ms (started: 2024-02-13 03:31:18 +00:00)


In [ ]:
log_path = os.path.join('Training', 'Logs')

In [ ]:
model = PPO("MlpPolicy", env, verbose=1, tensorboard_log=log_path)

In [ ]:
model.save('PPO')

In [ ]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)